name: latest blog post workflow

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull latest posts from Naver blog RSS
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.blog.naver.com/choehanmin.xml"
          max_post_count: 5
